# permissions for end users to edit hostnames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ddkube
    app.kubernetes.io/managed-by: kustomize
  name: hostname-editor-role
rules:
- apiGroups:
  - ddkube.foggy.day
  resources:
  - hostnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddkube.foggy.day
  resources:
  - hostnames/status
  verbs:
  - get
