---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ddkube.foggy.day
  resources:
  - hostnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddkube.foggy.day
  resources:
  - hostnames/finalizers
  verbs:
  - update
- apiGroups:
  - ddkube.foggy.day
  resources:
  - hostnames/status
  verbs:
  - get
  - patch
  - update
