apiVersion: ddkube.foggy.day/v1beta1
kind: Hostname
metadata:
  labels:
    app.kubernetes.io/name: ddkube
    app.kubernetes.io/managed-by: kustomize
  name: hostname-sample
spec:
  # TODO(user): Add fields here
